//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.08 at 12:44:39 PM CDT 
//


package PlantDataClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="stackLimit" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="growthTime" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="seed" type="{}seed"/&gt;
 *         &lt;element name="growthStages" type="{}growthStages"/&gt;
 *         &lt;element name="harvest" type="{}harvest"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "id",
    "stackLimit",
    "growthTime",
    "seed",
    "growthStages",
    "harvest"
})
@XmlRootElement(name = "plant")
public class PlantData {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected int id;
    @XmlElement(required = true)
    protected int stackLimit;
    @XmlElement(required = true)
    protected int growthTime;
    @XmlElement(required = true)
    protected Seed seed;
    @XmlElement(required = true)
    protected GrowthStages growthStages;
    @XmlElement(required = true)
    protected Harvest harvest;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the stackLimit property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getStackLimit() {
        return stackLimit;
    }

    /**
     * Sets the value of the stackLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setStackLimit(int value) {
        this.stackLimit = value;
    }

    /**
     * Gets the value of the growthTime property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getGrowthTime() {
        return growthTime;
    }

    /**
     * Sets the value of the growthTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setGrowthTime(int value) {
        this.growthTime = value;
    }

    /**
     * Gets the value of the seed property.
     * 
     * @return
     *     possible object is
     *     {@link Seed }
     *     
     */
    public Seed getSeed() {
        return seed;
    }

    /**
     * Sets the value of the seed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Seed }
     *     
     */
    public void setSeed(Seed value) {
        this.seed = value;
    }

    /**
     * Gets the value of the growthStages property.
     * 
     * @return
     *     possible object is
     *     {@link GrowthStages }
     *     
     */
    public GrowthStages getGrowthStages() {
        return growthStages;
    }

    /**
     * Sets the value of the growthStages property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrowthStages }
     *     
     */
    public void setGrowthStages(GrowthStages value) {
        this.growthStages = value;
    }

    /**
     * Gets the value of the harvest property.
     * 
     * @return
     *     possible object is
     *     {@link Harvest }
     *     
     */
    public Harvest getHarvest() {
        return harvest;
    }

    /**
     * Sets the value of the harvest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Harvest }
     *     
     */
    public void setHarvest(Harvest value) {
        this.harvest = value;
    }

}
