//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.08 at 12:44:39 PM CDT 
//


package PlantDataClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for seed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="seed"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="rarity" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="minLevel" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="sprite" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "seed", propOrder = {
    "cost",
    "rarity",
    "minLevel",
    "sprite"
})
public class Seed {

    @XmlElement(required = true)
    protected int cost;
    @XmlElement(required = true)
    protected double rarity;
    @XmlElement(required = true)
    protected int minLevel;
    @XmlElement(required = true)
    protected String sprite;

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setCost(int value) {
        this.cost = value;
    }

    /**
     * Gets the value of the rarity property.
     * 
     * @return
     *     possible object is
     *     {@link double }
     *     
     */
    public double getRarity() {
        return rarity;
    }

    /**
     * Sets the value of the rarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link double }
     *     
     */
    public void setRarity(double value) {
        this.rarity = value;
    }

    /**
     * Gets the value of the minLevel property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getMinLevel() {
        return minLevel;
    }

    /**
     * Sets the value of the minLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setMinLevel(int value) {
        this.minLevel = value;
    }

    /**
     * Gets the value of the sprite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSprite() {
        return sprite;
    }

    /**
     * Sets the value of the sprite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSprite(String value) {
        this.sprite = value;
    }

}
